---
title: "0412_adt_01"
author: "180212_my"
date: "2018년 4월 12일"
output: html_document
---
```{r}
library(data.table)
library(sqldf)
```

```{r}
df <- read.csv("C:\\Users\\202-22\\Documents\\R\\R2_Project\\R_Studio_exercise\\Project\\Data\\ad_tracking_data\\train_sample.csv", stringsAsFactors = F, na.string=c("", NA)) # na.string=c( ))
test <- read.csv("C:\\Users\\202-22\\Documents\\R\\R2_Project\\R_Studio_exercise\\Project\\Data\\ad_tracking_data\\test.csv", stringsAsFactors = F)
```

```{r}
head(df)
summary(df)
head(test)
```

```{r}
dim(df) ; dim(test)
```

```{r}
colnames(df)
colnames(test)
```

## date
```{r}
library(lubridate)
cl_ymd <- ymd(as.Date(df$click_time))
cl_year <- year(cl_ymd)
cl_month <- month(cl_ymd)
cl_day <- day(cl_ymd)
cl_hour <- as.POSIXlt(df$click_time)$hour
cl_min <- as.POSIXlt(df$click_time)$min
cl_sec <- as.POSIXlt(df$click_time)$sec


at_ymd <- ymd(as.Date(df$attributed_time))
at_year <- year(at_ymd)
at_month <- month(at_ymd)
at_day <- day(at_ymd)
at_hour <- as.POSIXlt(df$attributed_time)$hour
at_min <- as.POSIXlt(df$attributed_time)$min
at_sec <- as.POSIXlt(df$attributed_time)$sec

df2 <- cbind(df, cl_year, cl_month, cl_day, cl_hour, cl_min, cl_sec, at_year, at_month, at_day, at_hour, at_min, at_sec)
head(df2)
```

```{r}
barplot(table(df2$cl_day), ylim=c(0,35000), 
        names=c("2017-11-06", "2017-11-07", "2017-11-08", "2017-11-09"))
title(main="Clicked_time distribution by day")

## day 7 (tues)> day 8(wed) > day 9 (thus) > day 6 (mon)
```
```{r}
day_test <- data.frame(table(df2$cl_day))
```

```{r}

```

```{r}

```

```{r}
barplot(table(df2$cl_hour), ylim=c(0,7000))
title(main="Clicked_time distribution by hour")
```

```{r}
barplot(table(df2$at_day), ylim=c(0,100), 
        names=c("2017-11-06", "2017-11-07", "2017-11-08", "2017-11-09"))
title(main="Attributed_time distribution by day")
```

## missing value
```{r}
for (i in colnames(df2)){
  m_value <- sum(is.na(df2$i))
  print(m_value)
}  

sum(is.na(df2$ip))
sum(is.na(df2$app))
sum(is.na(df2$device))
sum(is.na(df2$os))
sum(is.na(df2$channel))
sum(is.na(df2$click_time))
sum(is.na(df2$attributed_time))  ## 99773/100000 missing values -> only 227 people downloaded app
sum(is.na(df2$is_attributed))
```


## barplot: categorical : 1/ table > 2/ barplot 
```{r}
t_ip <- table(df$ip)
t_app <- table(df$app)
t_device <-table(df$device)
t_os <- table(df$os)
t_chl <- table(df$channel)

barplot(t_ip)   ## there are many duplicated ips
barplot(t_app)
barplot(t_device)  # numbered device 1 is the most frequent value
barplot(t_os)
barplot(t_chl)
```

## how many of users with unique ip/app/device/os/channel?
```{r}
length(t_ip)     # 34857 (100000-34857)
length(t_app)    # 161
length(t_device) # 100
length(t_os)     # 130
length(t_chl)    # 161
```

## how many of category 1(app has been downloaded) from "is_attributed"  
```{r}
df2$is_attributed <- as.factor(df2$is_attributed)
summary(df)
sum(is.na(df$is_attributed))  # 0
t_appdown <- table(df$is_attributed)

b1 <- barplot(t_appdown, col=c("red", "green"),
          names =c("Not downloaded", "downloaded"),
          ylim=c(0, 100000)
          )
title("App download results")
title(xlab="App download status")
title(ylab="The number of app downloading") 
text(x = b1, y = df$is_attributed, label = t_appdown, pos = 3, cex = 0.8)

## There are more people who didn't download the app
```

```{r}
library(ggplot2)
appdown <- df$is_attributed[df$is_attributed == "1", ]

summary(df2)

g1 <- ggplot(df2, aes(x=cl_day, fill=is_attributed))
g2 <- geom_bar(position = "dodge", width=1)
g1+g2




```


```{r}
g3 <- ggplot(df2, aes(x=cl_hour, fill=is_attributed))
g4 <- geom_bar(position = "dodge", width=0.5)
g3 + g4
```

```{r}
g5 <- ggplot(df2, aes(x=at_day, fill=is_attributed))
g6 <- geom_bar(position = "dodge", width=.5)
g5+g6

```

