---
title: "0412_adt_01"
author: "180212_my"
date: "2018년 4월 12일"
output: html_document
---
```{r}
## library
library(data.table)
library(sqldf)
library(ggplot2)
```

```{r}
df <- read.csv("C:\\Users\\202-22\\Documents\\R\\R2_Project\\R_Studio_exercise\\Project\\Data\\ad_tracking_data\\train_sample.csv", stringsAsFactors = F, na.string=c("", NA)) # na.string=c( ))
test <- read.csv("C:\\Users\\202-22\\Documents\\R\\R2_Project\\R_Studio_exercise\\Project\\Data\\ad_tracking_data\\test.csv", stringsAsFactors = F)
```

```{r}
head(df)
summary(df)
head(test)
```

```{r}
dim(df) ; dim(test)
```

```{r}
colnames(df)
colnames(test)
```

## date
```{r}
library(lubridate)
cl_ymd <- ymd(as.Date(df$click_time))
cl_year <- year(cl_ymd)
cl_month <- month(cl_ymd)
cl_day <- day(cl_ymd)
cl_hour <- as.POSIXlt(df$click_time)$hour
cl_min <- as.POSIXlt(df$click_time)$min
cl_sec <- as.POSIXlt(df$click_time)$sec


at_ymd <- ymd(as.Date(df$attributed_time))
at_year <- year(at_ymd)
at_month <- month(at_ymd)
at_day <- day(at_ymd)
at_hour <- as.POSIXlt(df$attributed_time)$hour
at_min <- as.POSIXlt(df$attributed_time)$min
at_sec <- as.POSIXlt(df$attributed_time)$sec

df2 <- cbind(df, cl_year, cl_month, cl_day, cl_hour, cl_min, cl_sec, at_year, at_month, at_day, at_hour, at_min, at_sec)
head(df2)
```

```{r}
barplot(table(df2$cl_day), ylim=c(0,35000), 
        names=c("2017-11-06", "2017-11-07", "2017-11-08", "2017-11-09"))
title(main="Clicked_time distribution by day")

## day 7 (tues)> day 8(wed) > day 9 (thus) > day 6 (mon)
```
```{r}
ggplot(df2, aes(x=cl_day)) + geom_bar(fill=c("red", "orange", "green", "blue")) 
```

```{r}
ggplot(df2, aes(x=cl_hour)) + geom_bar() 

```

```{r}

```

```{r}

```

```{r}
barplot(table(df2$cl_hour), ylim=c(0,7000))
title(main="Clicked_time distribution by hour")
```

```{r}
barplot(table(df2$at_day), ylim=c(0,100), 
        names=c("2017-11-06", "2017-11-07", "2017-11-08", "2017-11-09"))
title(main="Attributed_time distribution by day")
```

## missing value
```{r}
for (i in colnames(df2)){
  m_value <- sum(is.na(df2$i))
  print(m_value)
}  

sum(is.na(df2$ip))
sum(is.na(df2$app))
sum(is.na(df2$device))
sum(is.na(df2$os))
sum(is.na(df2$channel))
sum(is.na(df2$click_time))
sum(is.na(df2$attributed_time))  ## 99773/100000 missing values -> only 227 people downloaded app
sum(is.na(df2$is_attributed))
```


## barplot: categorical : 1/ table > 2/ barplot 
```{r}
t_ip <- sort(table(df$ip), decreasing = T)
t_ip <- t_ip[1:10]

t_app <- sort(table(df$app), decreasing = T)
t_app <- t_app[1:10]

t_device <-sort(table(df$device), decreasing = T)
t_device <- t_device[1:10]

t_os <- sort(table(df$os), decreasing = T)
t_os <- t_os[1:10]

t_chl <- sort(table(df$channel), decreasing = T)
t_chl <- t_chl[1:10]

barplot(t_ip)   ## there are many duplicated ips
barplot(t_app)
barplot(t_device)  # numbered device 1 is the most frequent value
barplot(t_os)
barplot(t_chl)
```

## how many of users with unique ip/app/device/os/channel?
```{r}
length(t_ip)     # 34857 (100000-34857)
length(t_app)    # 161
length(t_device) # 100
length(t_os)     # 130
length(t_chl)    # 161
```

## how many of category 1(app has been downloaded) from "is_attributed"  
```{r}
df2$is_attributed <- as.factor(df2$is_attributed)
summary(df)
sum(is.na(df$is_attributed))  # 0
t_appdown <- table(df$is_attributed)

b1 <- barplot(t_appdown, col=c("red", "green"),
          names =c("Not downloaded", "downloaded"),
          ylim=c(0, 100000)
          )
title("App download results")
title(xlab="App download status")
title(ylab="The number of app downloading") 
text(x = b1, y = df$is_attributed, label = t_appdown, pos = 3, cex = 0.8)

## There are more people who didn't download the app
```

```{r}
g1 <- ggplot(df2, aes(x=cl_day, fill=is_attributed))
g2 <- geom_bar(position = "dodge", width=1)
g1+g2

```


```{r}
g3 <- ggplot(df2, aes(x=cl_hour, fill=is_attributed))
g4 <- geom_bar(position = "dodge", width=0.5)
g3 + g4
```

```{r}
a <- c(df2$ip, df2$app, df2$device, df2$os, df2$channel)
plot(c(df2$ip, df2$app, df2$device, df2$os, df2$channel))

plot(df2$ip, df2$device)
```

```{r}
df2_device1 <- df2[df2$device == "1", ]
device1_ip <- sort(table(df2_device1$ip), decreasing = T)
device1_ip <- device1_ip[1:10]
barplot(device1_ip)

```

```{r}
df2_device1 <- df2[df2$device == "1", ]
device1_ip <- sort(table(df2_device1$ip), decreasing = T)
device1_ip <- device1_ip[1:10]
barplot(device1_ip)

df2_device1 <- df2[df2$device == "1", ]
device1_os <- sort(table(df2_device1$os), decreasing = T)
device1_os <- device1_os[1:10]
barplot(device1_os)

df2_device1 <- df2[df2$device == "1", ]
device1_chl <- sort(table(df2_device1$channel), decreasing = T)
device1_chl <- device1_chl[1:10]
barplot(device1_chl)


bar_top10 <- funtion(data, variable) {
  a <- sort(table(data$variable), decreasing = T)
  a <- a[1:10]
  barplot(a)
}


```

## number of app downlowd for the most frequent device, #1
```{r}
df2_device1 <- df2[df2$device == "1", ]
device1_attr <- table(df2_device1$is_attributed)

b2 <- barplot(device1_attr, col=c("red", "green"),
          names =c("Not downloaded", "downloaded"))
title("App download results by device # 1")
title(xlab="App download status")
title(ylab="The number of app downloading by device #1") 
text(x = b2, y = df2_device1$is_attributed, label = device1_attr, pos = 3, cex = 0.8)
```

## number of app downlowd for the most frequent os, #19
```{r}
df2_os19 <- df2[df2$os == "19", ]
os19_attr <- table(df2_os19$is_attributed)

b3 <- barplot(os19_attr, col=c("red", "green"),
          names =c("Not downloaded", "downloaded"))
title("App download results by os # 19")
title(xlab="App download status")
title(ylab="The number of app downloading by os #19") 
text(x = b3, y = df2_os19$is_attributed, label = os19_attr, pos = 3, cex = 0.8)
```

```{r}
df2_chl280 <- df2[df2$channel == "280", ]
chl280_attr <- table(df2_chl280$is_attributed)

b4 <- barplot(chl280_attr, col=c("red", "green"),
          names =c("Not downloaded", "downloaded"))
title("App download results by channel # 280")
title(xlab="App download status")
title(ylab="The number of app downloading by channel #280") 
text(x = b4, y = df2_chl280$is_attributed, label = chl280_attr, pos = 3, cex = 0.8)
```
## device #1 & os #19 & channel # 280
```{r}
df2_doc <- df2[df2$device == "1" & df2$os == "19" & df2$channel == "280", ]
doc_attr <- table(df2_doc$is_attributed)

b5 <- barplot(doc_attr, col=c("red", "green"),
          names =c("Not downloaded", "downloaded"))
title("App download results by device #1 & os #19 & channel # 280")
title(xlab="App download status")
title(ylab="The number of app downloading by device #1 & os #19 & channel # 280") 
text(x = b5, y = df2_doc$is_attributed, label = doc_attr, pos = 3, cex = 0.8)
```

```{r}
df2$is_attributed <- as.factor(df2$is_attributed)
summary(df2)
ggplot(df2, aes(x=cl_hour, y=cl_day, color=is_attributed)) +geom_point()
```

```{r}
g3 <- ggplot(df2$is, aes(x=cl_hour, fill=is_attributed))
g4 <- geom_bar(position = "dodge", width=0.5)
g3 + g4
```

```{r}

```

```{r}

```

```{r}

```

