---
title: "Kernel"
author: "180212_my"
date: "2018년 4월 24일"
output: html_document
---
\
```{r}
install.packages(c("DT", "magrittr", "corrplot", "Rmisc", "ggalluvial", "ModelMetrics", "scales", "irlba", "forcats", "forecast", "TSA", "zoo"))
install.packages("corrplot")

library(data.table)
library(ggplot2)
library(DT)
library(magrittr)
library(corrplot)
library(Rmisc)
library(ggalluvial)
library(caret)
library(ModelMetrics)
require(scales)
library(irlba)
library(forcats)
library(forecast)
library(TSA)
library(zoo)
```

```{r}
getwd()
train <- fread("C:/Users/202-22/Documents/R/R2_Project/R_Studio_exercise/data/Ad_tracking/train_sample.csv", showProgress=F)
test <- fread("C:/Users/202-22/Documents/R/R2_Project/R_Studio_exercise/data/Ad_tracking/test.csv", showProgress=F)
```

```{r}
head(train)
```

```{r}
train[, -c("click_time", "attributed_time"), with=F] %>%

```

```{r}
train[, -c("click_time", "attributed_time"), with=F] %>%
  cor(method="spearman") %>%
  corrplot(type="lower", method="number", tl.col = "black", diag=F)
```

```{r}
train[, -c("click_time", "attributed_time"), with=F] %>%
  cor(method="pearson")
```

```{r}

```

```{r}

```

