---
title: "Untitled"
output: html_document
---

# Load libraries
```{r}
# install.packages(c('data.table', 'DT', 'magrittr', 'corrplot', 'Rmisc', 'ggalluvial', 'caret', 'ModelMetrics', 'scales', 'irlba', 'forcats', 'forecast', 'TSA', 'zoo'))
install.packages('xgboost')
library(data.table)
library(ggplot2)
library(DT)
library(magrittr)
library(corrplot)
library(Rmisc)
library(ggalluvial)
library(caret)
library(ModelMetrics)
library(scales)
library(irlba)
library(forcats)
library(forecast)
library(TSA)
library(zoo)
library(xgboost)
```

## 02. Load data
```{r}
# ktm
#train <- fread("C:/Users/202-22/Documents/R/R2_Project/R_Studio_exercise/data/Ad_tracking/train_sample.csv", showProgress=F)
#test <- fread("C:/Users/202-22/Documents/R/R2_Project/R_Studio_exercise/data/Ad_tracking/test.csv", showProgress=F)

# home
train <- fread('C:\\Users\\Kim\\Documents\\R\\Home_Review\\R_review\\ad_tracking\\train_sample.csv', showProgress = F)
test <- fread('C:\\Users\\Kim\\Documents\\R\\Home_Review\\R_review\\ad_tracking\\test.csv', showProgress = F)
```

## 03. Glimpse at the dataset
```{r}
head(train)
head(test)
```

```{r}
str(train)
```

## Number of unique values
```{r}
fea <- c("os", "channel", "device", "app", "attributed_time", "click_time", "ip")
train[, lapply(.SD, uniqueN), .SDcols = fea] %>%
  melt(variable.name = "features", value.name = "unique_values") %>%
  ggplot(aes(reorder(features, -unique_values), unique_values)) +
  geom_bar(stat ="identity", fill="steelblue") + 
  scale_y_log10(breaks = c(50,150,300, 500, 10000, 50000)) +
  geom_text(aes(label = unique_values), vjust = 1.6, color = "white", size=3.5) +
  theme_minimal() +
  labs(x = "features", y = "Number of unique values")
```

## Scatterplot - ip x is_attributed 
```{r}
ggplot(train, aes(x = seq_along(ip), y = ip)) +
  geom_point(aes(col=factor(is_attributed)), alpha=0.8, size=0.05) +
  theme_minimal() +
  scale_y_continuous(labels = comma) + 
  scale_x_continuous(name="index", labels = comma) +
  guides(color=guide_legend("is_attributed"))
```

```{r}
p1 <- train[, .N, by = os][order(-N)][1:10] %>% 
  ggplot(aes(reorder(os, -N), N)) +
  geom_bar(stat="identity", fill="steelblue") + 
  theme_minimal() +
  geom_text(aes(label = round(N / sum(N), 2)), vjust = 1.6, color = "white", size=2.5) +
  labs(x = "os") +
  theme(axis.text.x = element_text(angle=45, hjust = 1))

p2 <- train[, .N, by = channel][order(-N)][1:10] %>% 
  ggplot(aes(reorder(channel, -N), N)) +
  geom_bar(stat="identity", fill="steelblue") + 
  theme_minimal() +
  geom_text(aes(label = round(N / sum(N), 2)), vjust = 1.6, color = "white", size=2.5) +
  labs(x = "channel") +
  theme(axis.text.x = element_text(angle=45, hjust = 1))

p3 <- train[, .N, by = device][order(-N)][1:10] %>% 
  ggplot(aes(reorder(device, -N), N)) +
  geom_bar(stat="identity", fill="steelblue") + 
  theme_minimal() +
  geom_text(aes(label = round(N / sum(N), 2)), vjust = 1.6, color = "white", size=2.5) +
  labs(x = "device") +
  theme(axis.text.x = element_text(angle=45, hjust = 1))

p4 <- train[, .N, by = app][order(-N)][1:10] %>% 
  ggplot(aes(reorder(app, -N), N)) +
  geom_bar(stat="identity", fill="steelblue") + 
  theme_minimal() +
  geom_text(aes(label = round(N / sum(N), 2)), vjust = 1.6, color = "white", size=2.5) +
  labs(x = "app") +
  theme(axis.text.x = element_text(angle=45, hjust = 1))

multiplot(p1, p2, p3, p4, layout=matrix(1:4, 2,2))
```


## Pairwise correlations
```{r}
train[, -c("click_time", "attributed_time"), with=F] %>%
  cor(method = "spearman") %>%
  corrplot(type="lower", method = "number", tl.col = "black", diag=FALSE)
```


```{r}
X <- copy(train)[, -c("click_time", "attributed_time"), with=F][sample(.N, 5e4)]
fea <- c("ip", "app", "device", "os", "channel")

for (f in fea) {
  levels <- sort(names(which(table(X[[f]]) > 30)))
  X[[f]] <- factor(X[[f]], levels=levels)
}

m <- model.matrix(~.-1, X) %>% cor(method = "spearman")
m[is.na(m)] <- 0 
corrplot(m, type="full", method = "color", tl.pos = "n", cl.pos = "n", diag = T)
```

```{r}
diag(m)
```

```{r}
diag(m) <- 0
keep <- colSums(abs(m) > 0.75) > 0
corrplot(m[keep, keep], type = "lower", method = "number", tl.col = "black", diag = F, number.cex = 11/sum(keep))
```

## Time Patterns
```{r}
set.seed(0)
X <- copy(train)[, `:=`(hour = hour(click_time),
                        mday = mday(click_time),
                        click_time = as.POSIXct(click_time, format="%Y-%m-%d %H:%M:%S"),
                        is_attributed = factor(is_attributed))]
head(X)

```

```{r}
pt1 <- X[, .N, by = "hour"] %>% 
  ggplot(aes(hour, N)) + 
  geom_bar(stat="identity", fill="steelblue") + 
  ggtitle("Number of clicks per hour")+
  xlab("Hour") + 
  ylab("Number of clicks")+
  theme_minimal()

pt2 <- X[is_attributed==1, .N, by = c("hour", "is_attributed")] %>% 
  ggplot(aes(hour, N)) + 
  geom_bar(stat="identity", fill="orange") + 
  ggtitle("Number of downloads per hour")+
  xlab("Hour") + 
  ylab("Number of downloads")+
  theme_minimal()

multiplot(pt1, pt2, layout = matrix(1:2, 1, 2))  
```


```{r}
X[, .N, by = c("hour", "mday")
  ][, dt := as.POSIXct(paste0("2017-11-", mday, " ", hour), format="%Y-%m-%d %H")] %>% 
  ggplot(aes(dt, N)) + 
  geom_line(color="steelblue") +
  ggtitle("Clicks per hour")+
  xlab("Day-Hour") + 
  ylab("Number of clicks")+
  theme_minimal()+
  scale_x_datetime(labels = date_format("%d-%HH"), date_breaks = "8 hours")
```

```{r}
X[, .N, by = c("hour", "mday", "is_attributed")
  ][, dt := as.POSIXct(paste0("2017-11-", mday, " ", hour), format="%Y-%m-%d %H")] %>% 
  ggplot(aes(dt, N)) + 
  geom_line(aes(color = is_attributed), size = 0.5) +
  stat_smooth(aes(color = is_attributed))+
  ggtitle("Clicks per hour")+
  xlab("Day-Hour") + 
  ylab("Number of clicks")+
  scale_y_log10(breaks=c(5, 10, 100, 400, 700, 1000, 2000, 3000)) +
  theme_minimal()+
  scale_x_datetime(labels = date_format("%d-%HH"), date_breaks = "8 hours")
```

```{r}
dts <- data.table(freq=0, dt = seq(min(X$click_time),
                                   max(X$click_time), by="hour")
)[, dt:=as.POSIXct(as.character(dt), format="%Y-%m-%d %H")]

y <- X[, .N, by = c("hour", "mday", "is_attributed")
           ][, dt := as.POSIXct(paste0("2017-11-", mday, " ", hour), format="%Y-%m-%d %H")
             ][order(dt)
               ][is_attributed==1
                 ][dts, on = "dt"
                   ][is.na(N), N:=0] %>% 
  with(zoo(N, order.by=dt))


autoplot(y)+
  theme_minimal()+
  stat_smooth()+
  xlab("Day-Hour") + 
  ylab("Number of downloads")+
  scale_x_datetime(labels = date_format("%d-%HH"), date_breaks = "6 hours")
```

```{r}
m_aa <- auto.arima(y)
summary(m_aa)

autoplot(forecast(m_aa, h=12)) + theme_minimal()
```

```{r}
X <- copy(train)[, `:=`(hour = hour(click_time),
                        wday = wday(click_time),
                        minute = minute(click_time))
                 ][, c("click_time", "attributed_time", "is_attributed") := NULL]

head(X)
y <- train$is_attributed
```


```{r}
table(tri)
```

```{r}
tri <- createDataPartition(y, p = 0.6, list = F)  # show the selected index

X_val <- X[-tri] # valid data
y_val <- y[-tri]

X <- X[tri]

# create a new variable y in X
X$y <- factor(ifelse(train$is_attributed[tri]==0, "zero", "one")) 
str(X)
```

```{r}
ctrl <- trainControl(method = "cv", 
                     number = 4,
                     classProbs = T,
                     summaryFunction = twoClassSummary)

grid <- expand.grid(nrounds = 95, 
                    max_depth = 7, 
                    eta = 0.2, 
                    gamma = 0,
                    min_child_weight = 5,
                    colsample_bytree = 0.7, 
                    subsample = 0.7)

set.seed(0)
m_xgb <- train(y ~ ., data = X,
               method = "xgbTree",
               nthread = 8,
               metric = "ROC",
               tuneGrid = grid,
               trControl = ctrl)
getTrainPerf(m_xgb)
```

```{r}

```

